### ISSUE TITLE
segfault while loading World Driver Championship

### ISSUE THREAD

**Issue by dset0x** [mupen64plus/mupen64plus-core#678]
Hello, World Rally Championship consistently segfaults when loading WDC.

```
$ eix -I -c mupen | cut -d: -f1
[I] games-emulation/mupen64plus (2.5.9{tbz2}@22/09/19)
[I] games-emulation/mupen64plus-audio-sdl (2.5.9{tbz2}@22/09/19)
[I] games-emulation/mupen64plus-core (2.5.9(0/2-sdl2){tbz2}@22/09/19)
[I] games-emulation/mupen64plus-input-sdl (2.5.9{tbz2}@22/09/19)
[I] games-emulation/mupen64plus-rsp-hle (2.5.9{tbz2}@22/09/19)
[I] games-emulation/mupen64plus-ui-console (2.5.9{tbz2}@22/09/19)
[I] games-emulation/mupen64plus-video-glide64mk2 (2.5.9{tbz2}@22/09/19)
[I] games-emulation/mupen64plus-video-rice (2.5.9{tbz2}@22/09/19)
```
```
$ cd ~/src/GLideN64
$ git rev-parse HEAD
0068a0066b3110342bdf909aafac928876f3d381

$ cmake -DCMAKE_BUILD_TYPE=Debug -DTARGET_CPU=amd64 -DVEC4_OPT=On -DMUPENPLUSAPI=On .
$ cmake --build .
$ sudo cp ./plugin/Debug/mupen64plus-video-GLideN64.so /usr/lib64/mupen64plus # satisfy m64py
```

```
#0  0x0000000000000000 in ?? ()
#1  0x00007fffc969a3ce in opengl::GlGetStringiCommand::commandToExecute (this=0x555556b9eca0) at /home/user/src/GLideN64/src/Graphics/OpenGLContext/ThreadedOpenGl/opengl_WrappedFunctions.h:3690
#2  0x00007fffc967cddd in opengl::OpenGlCommand::performCommandSingleThreaded (this=0x555556b9eca0) at /home/user/src/GLideN64/src/Graphics/OpenGLContext/ThreadedOpenGl/opengl_Command.cpp:13
#3  0x00007fffc967fd7e in opengl::FunctionWrapper::executePriorityCommand (_command=std::shared_ptr<class opengl::OpenGlCommand> (use count 2, weak count 0) = {...}) at /home/user/src/GLideN64/src/Graphics/OpenGLContext/ThreadedOpenGl/opengl_Wrapper.cpp:36
#4  0x00007fffc9684c3e in opengl::FunctionWrapper::wrGetStringi (name=7939, index=0) at /home/user/src/GLideN64/src/Graphics/OpenGLContext/ThreadedOpenGl/opengl_Wrapper.cpp:1039
#5  0x00007fffc971d42a in opengl::Utils::isExtensionSupported (_glinfo=..., extension=0x7fffc9818140 "GL_ARB_fragment_shader_interlock") at /home/user/src/GLideN64/src/Graphics/OpenGLContext/opengl_Utils.cpp:16
#6  0x00007fffc96f0559 in opengl::GLInfo::init (this=0x555556e16c90) at /home/user/src/GLideN64/src/Graphics/OpenGLContext/opengl_GLInfo.cpp:80
#7  0x00007fffc96ea486 in opengl::ContextImpl::init (this=0x555556e16c10) at /home/user/src/GLideN64/src/Graphics/OpenGLContext/opengl_ContextImpl.cpp:39
#8  0x00007fffc9679ffc in graphics::Context::init (this=0x7fffc9f061c0 <gfxContext>) at /home/user/src/GLideN64/src/Graphics/Context.cpp:29
#9  0x00007fffc9628ea2 in DisplayWindow::start (this=0x7fffc9f086a0 <DisplayWindow::get()::video>) at /home/user/src/GLideN64/src/DisplayWindow.cpp:17
#10 0x00007fffc9679b18 in PluginAPI::RomOpen (this=0x7fffc9f061a8 <PluginAPI::get()::api>) at /home/user/src/GLideN64/src/common/CommonAPIImpl_common.cpp:210
#11 0x00007fffc97659e1 in RomOpen () at /home/user/src/GLideN64/src/MupenPlusPluginAPI.cpp:15
#12 0x00007fffed27b11b in main_run () from /usr/lib64/libmupen64plus.so.2
#13 0x00007fffed24067f in CoreDoCommand () from /usr/lib64/libmupen64plus.so.2
#14 0x000055555555c32c in main ()
```

Thank you for all your work! Let me know if you could use any more output.

**Comment by dset0x** [comment]
Er, wrong repository. Apologies for the noise.
