### ISSUE TITLE
libdragon games only work with Pure Interpreter

### ISSUE THREAD

**Issue by loganmc10** [mupen64plus/mupen64plus-core#738]
Here are 2 example ROMs:
(DOOM Shareware port to N64)
[DOOMSHAREWARE.zip](https://github.com/mupen64plus/mupen64plus-core/files/4378824/DOOMSHAREWARE.zip)

(FlappyBird port to N64)
[FlappyBird.zip](https://github.com/mupen64plus/mupen64plus-core/files/4378829/FlappyBird.zip)

Both of these games were created with the "libdragon" homebrew SDK. They work with the Pure Interpreter, but not the Cached Interpreter.

You need to use CXD4 RSP + Angrylion to play them, or the very latest master of GLideN64

**Comment by loganmc10** [comment]
I don't fully understand how the compare core feature works, but I ran it using FlappyBird using Pure Interpreter, set to "send" mode, and then again using the Cached interpreter, using "recv" mode, and this was the output:

```
Compare #7940983  old_op: 0 op: 0
err:    gpr  addr:80000184	 My: reg[8]=241004e5	 Ref: reg[8]=241004e1	 My: reg[27]=1	 Ref: reg[27]=ffffffff80010000
```

**Comment by loganmc10** [comment]
Output for Donkey Kong 64 (U) [f2]:

```
Compare #8886165  old_op: 0 op: 0
err:    gpr  addr:80000184	 My: reg[8]=5	 Ref: reg[8]=1	 My: reg[26]=ffffffffdeadbeef	 Ref: reg[26]=ffffffff80100000
```

**Comment by loganmc10** [comment]
And here is the backtrace from the new dynarec:

```
#1  0x00007ffff66af8d9 in abort () at /lib64/libc.so.6
#2  0x00007ffff66af7a9 in _nl_load_domain.cold () at /lib64/libc.so.6
#3  0x00007ffff66bea66 in annobin_assert.c_end () at /lib64/libc.so.6
#4  0x00007fffb8348fe6 in output_modrm (mod=3 '\003', rm=0 '\000', ext=255 '\377') at ../../src/device/r4300/new_dynarec/x64/assem_x64.c:712
#5  0x00007fffb8349278 in emit_mov (rs=-1, rt=0) at ../../src/device/r4300/new_dynarec/x64/assem_x64.c:749
#6  0x00007fffb836141e in storelr_assemble (i=120, i_regs=0x7fffbc25b4a0 <regs+16320>) at ../../src/device/r4300/new_dynarec/new_dynarec.c:4253
#7  0x00007fffb8385f9b in new_recompile_block (addr=-2147472536) at ../../src/device/r4300/new_dynarec/new_dynarec.c:10668
#8  0x00007fffb8357fc8 in dyna_linker (src=0x7fffbce85fab <g_dev+9486251>, vaddr=2147494760) at ../../src/device/r4300/new_dynarec/new_dynarec.c:2002
#9  0x00007fffbce86502 in g_dev () at /home/loganmc10/m64p/mupen64plus/libmupen64plus.so.2
#10 0x0460002000000003 in  ()
#11 0x00007fffbfe84660 in g_dev () at /home/loganmc10/m64p/mupen64plus/libmupen64plus.so.2
#12 0x00007fffd4c347e0 in  ()
#13 0x00007fffb831e077 in r4300_write_aligned_wordPython Exception <class 'gdb.MemoryError'> Cannot access memory at address 0x807ffca8: 

src/device/r4300/new_dynarec/x64/assem_x64.c:712: output_modrm: Assertion `ext<8' failed.
```

**Comment by loganmc10** [comment]
Perhaps a clue for this one:
in ```invalidate_cached_code_hacktarux```, if I force this path:

```
memset(r4300->cached_interp.invalid_code, 1, 0x100000);
```

Then FlappyBird works, albeit very slowly. So it seems like we aren't invalidating cached code when we should be?
