### ISSUE TITLE
"Densha De Go! 64" won't boot

### ISSUE THREAD

**Issue by izumariu** [mupen64plus/mupen64plus-core#765]
Hello, I am trying to get this great Japanese game to run. I have compiled the newest version of mupen64plus and it works perfectly fine with other games like SM64. For the video plugin, I'm using glide64mk2. This is the output log when trying to open DDG:

```
 __  __                         __   _  _   ____  _            
|  \/  |_   _ _ __   ___ _ __  / /_ | || | |  _ \| |_   _ ___  
| |\/| | | | | '_ \ / _ \ '_ \| '_ \| || |_| |_) | | | | / __| 
| |  | | |_| | |_) |  __/ | | | (_) |__   _|  __/| | |_| \__ \ 
|_|  |_|\__,_| .__/ \___|_| |_|\___/   |_| |_|   |_|\__,_|___/ 
             |_|                                               

M64Py - A frontend for Mupen64Plus version 0.2.5

Frontend: INFO: attached to library 'Mupen64Plus Core' version 2.5.0
Frontend: INFO: includes support for Dynamic Recompiler.
Frontend: INFO: includes support for MIPS r4300 Debugger.
Frontend: INFO: video extension enabled
Input: parsing error in MouseSensitivity parameter for controller 1
Core: Goodname: Densha de Go! 64 (J) [!]
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 237, in 'calling callback function'
  File "/home/izu/.local/lib/python3.8/site-packages/m64py-0.2.5-py3.8.egg/m64py/core/core.py", line 39, in debug_callback
    sys.stderr.write("%s: %s\n" % (context.decode(), message.decode()))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 6: invalid continuation byte
Core: MD5: 772FA166E5DB51EFFC77FB8D832AC4D2
Core: CRC: 17C54A61 4A83F2E7
Core: Imagetype: .z64 (native)
Core: Rom size: 33554432 bytes (or 32 Mb or 256 Megabits)
Core: Version: 144A
Core: Manufacturer: Nintendo
Core: Country: Japan
Video: opening /usr/share/games/mupen64plus/Glide64mk2.ini

INI_FindSection trying to find name for DEFAULT
Video: 3DNOW! detected.

Frontend: INFO: using Video plugin: 'Glide64mk2 Video Plugin' v2.5.0
Frontend: INFO: using Audio plugin: 'Mupen64Plus SDL Audio Plugin' v2.5.0
Input: 1 SDL joysticks were found.
Input: parsing error in MouseSensitivity parameter for controller 1
Input: N64 Controller #1: Using manual config for SDL joystick 0
Input: 1 controller(s) found, 1 plugged in and usable in the emulator
Frontend: INFO: no cheat codes found for ROM image b'\xc3\xde\xdd\xbc\xac\xc3\xdeGO!64'
Input: Couldn't open rumble support for joystick #1
Input: Couldn't open rumble support for joystick #2
Input: Couldn't open rumble support for joystick #3
Input: Couldn't open rumble support for joystick #4
Input: Mupen64Plus SDL Input Plugin version 2.5.0 initialized.
Frontend: INFO: using Input plugin: 'Mupen64Plus SDL Input Plugin' v2.5.0
Frontend: INFO: using RSP plugin: 'Hacktarux/Azimer High-Level Emulation RSP Plugin' v2.5.0
INI_FindSection trying to find name for DEFAULT
INI_FindSection trying to find name for ��ݼ���GO!64
Video: Using TEXUMA extension.

Could not find [��ݼ���GO!64] section in INI file!&ConfigOpenSection is 0x7fe281d3fca0
(II) Setting video mode 1296x972...
packed pixels extension used
NPOT extension used
use_fbo 1
Video: InitCombine() 
Video: extensions 
Video: initialized.
Video: 

Audio: Initializing SDL audio subsystem...
Input: Couldn't open rumble support for joystick #1
Input: Couldn't open rumble support for joystick #2
Input: Couldn't open rumble support for joystick #3
Input: Couldn't open rumble support for joystick #4
Core: Starting R4300 emulator: Cached Interpreter
INI_FindSection trying to find name for UCODE
```
After this, the screen remains black, there aren't any errors, just pure silence. The log doesn't continue either.
Apparently, it has some issues with the game "ID" since it's not "proper UTF-8". I am also trying to get the English patch to work; and it seems like the checksums are indeed matching.

**Comment by Jj0YzL5nvJ** [comment]
Well, [it works for me](https://imgur.com/a/ANiqatU). But I prefer [angrylion-plus](https://github.com/ata4/angrylion-rdp-plus) and [GLideN64](https://github.com/gonetz/GLideN64).
Glide64mk2 exhibits Z-fighting issues on SM64. Version 2.5.0 isn't exactly new...

**Comment by spinnylights** [comment]
I just built from the [latest commit](https://github.com/mupen64plus/mupen64plus-core/commit/16cced5c6728bc3537f8959642dcd38ce1ce0590) and everything with this game seems to work for me as well. (This is under Arch Linux kernel v. 5.8.1, glide64mk2 for video, SDL -> ALSA for sound.) However, it does not work for me under 2.5.0 either, and in the same manner—black screen, no audio, no crash or hang (some deeply suspicious output can be seen with verbose logging on but otherwise nothing out-of-the-ordinary appears).

Since it seems like the problem has already been fixed, I don't imagine anything needs to be done to the code in this case, but anyone who runs into this issue should either try building from a recent commit and using that instead, or maybe using the [2.5.9 beta](https://github.com/mupen64plus/mupen64plus-core/releases/tag/2.5.9). I haven't tried 2.5.9 but I wouldn't be surprised if it works there too.

> Version 2.5.0 isn't exactly new...

It's still the latest stable release; it's only natural to expect people to use it.
